import type { Locale } from './useAssistant';

/**
 * Everything the widget says in its own voice, as opposed to the answers.
 *
 * Both halves have to move together. A Kiswahili answer sitting under an
 * English "Need a person?" is half a translation, and half a translation reads
 * worse than none — it says the Kiswahili was a trick the machine did rather
 * than a language anybody here speaks.
 *
 * English is complete and is the base: every other language is written as a
 * partial and laid over it, so a word nobody has translated yet shows up in
 * English instead of as a blank. That is also what lets a language be added
 * with the dozen strings that matter first and filled in later.
 *
 * Languages beyond these twelve are still answered — the model writes in
 * whatever the visitor writes — and just wear English furniture.
 */

type Quick = { label: string; ask: string };

const en = {
    title: 'Auto Resellers Hub AI',
    status: 'Answers instantly',
    open: 'Open the Auto Resellers Hub assistant',
    close: 'Close',
    restart: 'Start over',
    send: 'Send',
    placeholder: 'Ask anything…',
    footnote: 'AI can make mistakes — check prices on the pricing page',
    greeting: 'Hi there 👋',
    thinking: 'Thinking',

    peekTitle: 'Questions about the bots?',
    peekBody: 'Ask me — in any language.',

    language: 'Language',
    autoDetect: 'Auto-detect',
    copy: 'Copy answer',
    copied: 'Copied',
    listen: 'Speak your question',
    listening: 'Listening…',
    popular: 'Popular questions',
    tryTitle: 'Try the real bot',
    tryBody: 'Chat with it on a phone screen. No signup.',

    needPerson: 'Need a person?',
    whatsapp: 'WhatsApp',
    leaveDetails: 'Leave details',

    failed: 'That did not go through. Try again in a moment, or reach us on WhatsApp.',
    askAgain: 'Ask again',
    slowDown: "You are asking quite fast — give me a few seconds and try again.",

    leadTitle: 'Leave your details',
    leadBody: 'We will reply on WhatsApp. Your question so far comes with it.',
    leadNoChat:
        'This form needs a chat to attach to, and nothing went through yet. Ask your question above first, or reach us on WhatsApp.',
    leadName: 'Your name',
    leadPhone: 'WhatsApp number',
    leadExtra: 'Anything to add',
    optional: '(optional)',
    back: 'Back',
    sendToSupport: 'Send to support',
    leadFailed: 'That did not send. Try again, or reach us on WhatsApp.',

    quick: {
        orderBot: { label: 'What is Order Bot?', ask: 'What is Order Bot?' },
        supportBot: { label: 'What is Support Bot?', ask: 'What is Support Bot?' },
        pricing: { label: 'How much does it cost?', ask: 'How much does it cost?' },
        start: { label: 'How do I get started?', ask: 'How do I get started?' },
        ownNumber: { label: 'Use my own number?', ask: 'Can I use my own WhatsApp number?' },
        languages: { label: 'Which languages?', ask: 'What languages does the bot speak?' },
    } as Record<string, Quick>,

    // Keyed on the path the visitor is reading, so the opening line uses the
    // one thing we already know about them.
    openers: {
        pricing: 'Comparing the plans? I can explain what each one does and what it costs.',
        features: 'Happy to go deeper on any of these — just ask.',
        apiDocs: 'Questions about the API, or about connecting your panel? Ask away.',
        blog: 'Ask me anything about the bots while you read.',
        contact: 'I can probably answer it right here — and put you through if not.',
        try: 'Tap around the practice chat — and ask me anything you are unsure about.',
        home: "I'm the Auto Resellers Hub assistant. Ask me anything — what a panel is, how setup works, what it costs. I answer in your language.",
    },
};

export type Strings = typeof en;

type Partial2<T> = { [K in keyof T]?: T[K] extends object ? Partial<T[K]> : T[K] };

const sw: Partial2<Strings> = {
    status: 'Inajibu papo hapo',
    open: 'Fungua msaidizi wa Auto Resellers Hub',
    close: 'Funga',
    restart: 'Anza upya',
    send: 'Tuma',
    placeholder: 'Uliza chochote…',
    footnote: 'AI inaweza kukosea — angalia bei kwenye ukurasa wa bei',
    greeting: 'Habari 👋',
    thinking: 'Inafikiri',
    peekTitle: 'Una swali kuhusu bots?',
    peekBody: 'Niulize — kwa lugha yoyote.',
    language: 'Lugha',
    autoDetect: 'Tambua yenyewe',
    copy: 'Nakili jibu',
    copied: 'Imenakiliwa',
    listen: 'Sema swali lako',
    listening: 'Nasikiliza…',
    popular: 'Maswali maarufu',
    tryTitle: 'Jaribu bot halisi',
    tryBody: 'Zungumza nayo kwenye skrini ya simu. Bila kujisajili.',
    needPerson: 'Unahitaji mtu?',
    leaveDetails: 'Acha taarifa',
    failed: 'Haikupita. Jaribu tena baada ya muda, au tufikie kwenye WhatsApp.',
    askAgain: 'Uliza tena',
    slowDown: "Unauliza haraka kidogo — nipe sekunde chache kisha ujaribu tena.",
    leadTitle: 'Acha taarifa zako',
    leadBody: 'Tutakujibu kwenye WhatsApp. Swali lako linakwenda pamoja nazo.',
    leadNoChat:
        'Fomu hii inahitaji mazungumzo ya kuambatanisha nayo, na hakuna kilichopita bado. Uliza swali lako hapo juu kwanza, au tufikie kwenye WhatsApp.',
    leadName: 'Jina lako',
    leadPhone: 'Namba ya WhatsApp',
    leadExtra: 'Kuna la kuongeza',
    optional: '(si lazima)',
    back: 'Rudi',
    sendToSupport: 'Tuma kwa support',
    leadFailed: 'Haikutumwa. Jaribu tena, au tufikie kwenye WhatsApp.',
    quick: {
        orderBot: { label: 'Order Bot ni nini?', ask: 'Order Bot ni nini?' },
        supportBot: { label: 'Support Bot ni nini?', ask: 'Support Bot ni nini?' },
        pricing: { label: 'Bei ni kiasi gani?', ask: 'Bei ni kiasi gani?' },
        start: { label: 'Naanzaje?', ask: 'Ninawezaje kuanza?' },
        ownNumber: { label: 'Namba yangu mwenyewe?', ask: 'Naweza kutumia namba yangu ya WhatsApp?' },
        languages: { label: 'Lugha gani?', ask: 'Bot inazungumza lugha gani?' },
    },
    openers: {
        pricing: 'Unalinganisha bei? Naweza kueleza kila huduma inafanya nini na inagharimu kiasi gani.',
        features: 'Niko tayari kueleza zaidi kuhusu lolote hapa — niulize tu.',
        apiDocs: 'Una swali kuhusu API, au kuunganisha panel yako? Niulize.',
        blog: 'Niulize chochote kuhusu bots wakati unasoma.',
        contact: 'Pengine naweza kukujibu hapa hapa — na kama sivyo, nitakuunganisha na mtu.',
        try: 'Zunguka kwenye practice chat — na uniulize chochote usichokielewa.',
        home: 'Mimi ni msaidizi wa Auto Resellers Hub. Niulize chochote — panel ni nini, usanidi unafanyaje kazi, bei ni kiasi gani. Najibu kwa lugha yako.',
    },
};

const fr: Partial2<Strings> = {
    status: 'Répond instantanément',
    open: "Ouvrir l'assistant Auto Resellers Hub",
    close: 'Fermer',
    restart: 'Recommencer',
    send: 'Envoyer',
    placeholder: 'Posez votre question…',
    footnote: "L'IA peut se tromper — vérifiez les prix sur la page des tarifs",
    greeting: 'Bonjour 👋',
    thinking: 'Réflexion',
    peekTitle: 'Une question sur les bots ?',
    peekBody: 'Posez-la-moi — dans votre langue.',
    language: 'Langue',
    autoDetect: 'Détection auto',
    copy: 'Copier la réponse',
    copied: 'Copié',
    listen: 'Dicter votre question',
    listening: "J'écoute…",
    popular: 'Questions fréquentes',
    tryTitle: 'Essayer le vrai bot',
    tryBody: "Discutez avec lui sur un écran de téléphone. Sans inscription.",
    needPerson: "Besoin d'une personne ?",
    leaveDetails: 'Laisser mes coordonnées',
    failed: "Cela n'a pas abouti. Réessayez dans un instant, ou écrivez-nous sur WhatsApp.",
    askAgain: 'Redemander',
    slowDown: "Vous posez vos questions très vite — patientez quelques secondes et réessayez.",
    leadTitle: 'Laissez vos coordonnées',
    leadBody: 'Nous répondrons sur WhatsApp. Votre question jusqu\'ici est jointe.',
    leadName: 'Votre nom',
    leadPhone: 'Numéro WhatsApp',
    leadExtra: 'Autre chose à ajouter',
    optional: '(facultatif)',
    back: 'Retour',
    sendToSupport: 'Envoyer au support',
    leadFailed: "L'envoi a échoué. Réessayez, ou écrivez-nous sur WhatsApp.",
    quick: {
        orderBot: { label: "Qu'est-ce que Order Bot ?", ask: "Qu'est-ce que Order Bot ?" },
        supportBot: { label: "Qu'est-ce que Support Bot ?", ask: "Qu'est-ce que Support Bot ?" },
        pricing: { label: 'Combien ça coûte ?', ask: 'Combien ça coûte ?' },
        start: { label: 'Comment commencer ?', ask: 'Comment puis-je commencer ?' },
        ownNumber: { label: 'Mon propre numéro ?', ask: 'Puis-je utiliser mon propre numéro WhatsApp ?' },
        languages: { label: 'Quelles langues ?', ask: 'Quelles langues le bot parle-t-il ?' },
    },
    openers: {
        home: "Je suis l'assistant d'Auto Resellers Hub. Demandez-moi n'importe quoi : ce qu'est un panel, comment se passe l'installation, combien ça coûte. Je réponds dans votre langue.",
        pricing: 'Vous comparez les offres ? Je peux expliquer ce que fait chacune et ce qu\'elle coûte.',
        try: "Explorez le chat d'essai — et posez-moi toutes vos questions.",
    },
};

const es: Partial2<Strings> = {
    status: 'Responde al instante',
    open: 'Abrir el asistente de Auto Resellers Hub',
    close: 'Cerrar',
    restart: 'Empezar de nuevo',
    send: 'Enviar',
    placeholder: 'Pregunta lo que quieras…',
    footnote: 'La IA puede equivocarse — revisa los precios en la página de precios',
    greeting: 'Hola 👋',
    thinking: 'Pensando',
    peekTitle: '¿Dudas sobre los bots?',
    peekBody: 'Pregúntame — en tu idioma.',
    language: 'Idioma',
    autoDetect: 'Detectar automáticamente',
    copy: 'Copiar respuesta',
    copied: 'Copiado',
    listen: 'Dicta tu pregunta',
    listening: 'Escuchando…',
    popular: 'Preguntas frecuentes',
    tryTitle: 'Prueba el bot real',
    tryBody: 'Chatea con él en la pantalla de un teléfono. Sin registrarte.',
    needPerson: '¿Necesitas a una persona?',
    leaveDetails: 'Dejar mis datos',
    failed: 'No se envió. Inténtalo de nuevo en un momento, o escríbenos por WhatsApp.',
    askAgain: 'Preguntar de nuevo',
    slowDown: "Estás preguntando muy rápido — dame unos segundos e inténtalo de nuevo.",
    leadTitle: 'Deja tus datos',
    leadBody: 'Te responderemos por WhatsApp. Tu pregunta hasta ahora va incluida.',
    leadName: 'Tu nombre',
    leadPhone: 'Número de WhatsApp',
    leadExtra: 'Algo más que añadir',
    optional: '(opcional)',
    back: 'Volver',
    sendToSupport: 'Enviar a soporte',
    leadFailed: 'No se pudo enviar. Inténtalo de nuevo, o escríbenos por WhatsApp.',
    quick: {
        orderBot: { label: '¿Qué es Order Bot?', ask: '¿Qué es Order Bot?' },
        supportBot: { label: '¿Qué es Support Bot?', ask: '¿Qué es Support Bot?' },
        pricing: { label: '¿Cuánto cuesta?', ask: '¿Cuánto cuesta?' },
        start: { label: '¿Cómo empiezo?', ask: '¿Cómo empiezo?' },
        ownNumber: { label: '¿Mi propio número?', ask: '¿Puedo usar mi propio número de WhatsApp?' },
        languages: { label: '¿Qué idiomas?', ask: '¿Qué idiomas habla el bot?' },
    },
    openers: {
        home: 'Soy el asistente de Auto Resellers Hub. Pregúntame lo que quieras: qué es un panel, cómo es la configuración, cuánto cuesta. Respondo en tu idioma.',
        pricing: '¿Comparando planes? Puedo explicarte qué hace cada uno y cuánto cuesta.',
        try: 'Explora el chat de prueba — y pregúntame lo que no tengas claro.',
    },
};

const pt: Partial2<Strings> = {
    status: 'Responde na hora',
    open: 'Abrir o assistente da Auto Resellers Hub',
    close: 'Fechar',
    restart: 'Recomeçar',
    send: 'Enviar',
    placeholder: 'Pergunte o que quiser…',
    footnote: 'A IA pode errar — confira os preços na página de preços',
    greeting: 'Olá 👋',
    thinking: 'Pensando',
    peekTitle: 'Dúvidas sobre os bots?',
    peekBody: 'Pergunte — no seu idioma.',
    language: 'Idioma',
    autoDetect: 'Detectar automaticamente',
    copy: 'Copiar resposta',
    copied: 'Copiado',
    listen: 'Dite sua pergunta',
    listening: 'Ouvindo…',
    popular: 'Perguntas frequentes',
    tryTitle: 'Experimente o bot de verdade',
    tryBody: 'Converse com ele na tela de um celular. Sem cadastro.',
    needPerson: 'Precisa falar com uma pessoa?',
    leaveDetails: 'Deixar meus dados',
    failed: 'Não foi enviado. Tente de novo em instantes, ou fale conosco no WhatsApp.',
    askAgain: 'Perguntar de novo',
    slowDown: "Você está perguntando muito rápido — espere alguns segundos e tente de novo.",
    leadTitle: 'Deixe seus dados',
    leadBody: 'Responderemos no WhatsApp. Sua pergunta até agora vai junto.',
    leadName: 'Seu nome',
    leadPhone: 'Número do WhatsApp',
    leadExtra: 'Algo a acrescentar',
    optional: '(opcional)',
    back: 'Voltar',
    sendToSupport: 'Enviar ao suporte',
    leadFailed: 'Não foi possível enviar. Tente de novo, ou fale conosco no WhatsApp.',
    quick: {
        orderBot: { label: 'O que é o Order Bot?', ask: 'O que é o Order Bot?' },
        supportBot: { label: 'O que é o Support Bot?', ask: 'O que é o Support Bot?' },
        pricing: { label: 'Quanto custa?', ask: 'Quanto custa?' },
        start: { label: 'Como começar?', ask: 'Como eu começo?' },
        ownNumber: { label: 'Meu próprio número?', ask: 'Posso usar meu próprio número de WhatsApp?' },
        languages: { label: 'Quais idiomas?', ask: 'Quais idiomas o bot fala?' },
    },
    openers: {
        home: 'Sou o assistente da Auto Resellers Hub. Pergunte o que quiser: o que é um painel, como funciona a configuração, quanto custa. Respondo no seu idioma.',
        pricing: 'Comparando planos? Posso explicar o que cada um faz e quanto custa.',
        try: 'Explore o chat de teste — e me pergunte o que não ficou claro.',
    },
};

const ar: Partial2<Strings> = {
    status: 'يجيب فورًا',
    open: 'افتح مساعد Auto Resellers Hub',
    close: 'إغلاق',
    restart: 'ابدأ من جديد',
    send: 'إرسال',
    placeholder: 'اسأل ما تشاء…',
    footnote: 'قد يخطئ الذكاء الاصطناعي — تحقق من الأسعار في صفحة الأسعار',
    greeting: 'مرحبًا 👋',
    thinking: 'يفكر',
    peekTitle: 'أسئلة حول البوتات؟',
    peekBody: 'اسألني — بلغتك.',
    language: 'اللغة',
    autoDetect: 'كشف تلقائي',
    copy: 'نسخ الإجابة',
    copied: 'تم النسخ',
    listen: 'انطق سؤالك',
    listening: 'أستمع…',
    popular: 'أسئلة شائعة',
    tryTitle: 'جرّب البوت الحقيقي',
    tryBody: 'تحدّث معه على شاشة هاتف. بدون تسجيل.',
    needPerson: 'تحتاج إلى شخص؟',
    leaveDetails: 'اترك بياناتك',
    failed: 'لم يتم الإرسال. حاول مرة أخرى بعد قليل، أو راسلنا على واتساب.',
    askAgain: 'اسأل مرة أخرى',
    slowDown: "أنت تسأل بسرعة كبيرة — انتظر بضع ثوانٍ ثم حاول مرة أخرى.",
    leadTitle: 'اترك بياناتك',
    leadBody: 'سنرد عليك عبر واتساب. سؤالك حتى الآن مرفق.',
    leadName: 'اسمك',
    leadPhone: 'رقم واتساب',
    leadExtra: 'أي إضافة',
    optional: '(اختياري)',
    back: 'رجوع',
    sendToSupport: 'إرسال إلى الدعم',
    leadFailed: 'تعذّر الإرسال. حاول مرة أخرى، أو راسلنا على واتساب.',
    quick: {
        orderBot: { label: 'ما هو Order Bot؟', ask: 'ما هو Order Bot؟' },
        supportBot: { label: 'ما هو Support Bot؟', ask: 'ما هو Support Bot؟' },
        pricing: { label: 'كم السعر؟', ask: 'كم يكلّف؟' },
        start: { label: 'كيف أبدأ؟', ask: 'كيف أبدأ؟' },
        ownNumber: { label: 'رقمي الخاص؟', ask: 'هل يمكنني استخدام رقم واتساب الخاص بي؟' },
        languages: { label: 'ما اللغات؟', ask: 'ما اللغات التي يتحدثها البوت؟' },
    },
    openers: {
        home: 'أنا مساعد Auto Resellers Hub. اسألني عن أي شيء: ما هي اللوحة (panel)، وكيف يتم الإعداد، وكم التكلفة. أجيب بلغتك.',
        pricing: 'تقارن بين الباقات؟ يمكنني شرح ما تفعله كل باقة وتكلفتها.',
        try: 'جرّب محادثة التجربة — واسألني عمّا لا تفهمه.',
    },
};

const hi: Partial2<Strings> = {
    status: 'तुरंत जवाब देता है',
    open: 'Auto Resellers Hub असिस्टेंट खोलें',
    close: 'बंद करें',
    restart: 'फिर से शुरू करें',
    send: 'भेजें',
    placeholder: 'कुछ भी पूछें…',
    footnote: 'AI गलती कर सकता है — कीमतें प्राइसिंग पेज पर जाँचें',
    greeting: 'नमस्ते 👋',
    thinking: 'सोच रहा है',
    peekTitle: 'बॉट्स के बारे में सवाल?',
    peekBody: 'मुझसे पूछें — अपनी भाषा में।',
    language: 'भाषा',
    autoDetect: 'अपने आप पहचानें',
    copy: 'जवाब कॉपी करें',
    copied: 'कॉपी हो गया',
    listen: 'अपना सवाल बोलें',
    listening: 'सुन रहा हूँ…',
    popular: 'आम सवाल',
    tryTitle: 'असली बॉट आज़माएँ',
    tryBody: 'फ़ोन की स्क्रीन पर इससे चैट करें। साइनअप नहीं चाहिए।',
    needPerson: 'किसी व्यक्ति से बात करनी है?',
    leaveDetails: 'अपनी जानकारी दें',
    failed: 'यह नहीं गया। थोड़ी देर में फिर कोशिश करें, या WhatsApp पर संपर्क करें।',
    askAgain: 'फिर से पूछें',
    slowDown: "आप बहुत तेज़ी से पूछ रहे हैं — कुछ सेकंड रुककर फिर कोशिश करें।",
    leadTitle: 'अपनी जानकारी दें',
    leadBody: 'हम WhatsApp पर जवाब देंगे। अब तक का आपका सवाल साथ जाएगा।',
    leadName: 'आपका नाम',
    leadPhone: 'WhatsApp नंबर',
    leadExtra: 'कुछ जोड़ना है',
    optional: '(वैकल्पिक)',
    back: 'वापस',
    sendToSupport: 'सपोर्ट को भेजें',
    leadFailed: 'भेजा नहीं जा सका। फिर कोशिश करें, या WhatsApp पर संपर्क करें।',
    quick: {
        orderBot: { label: 'Order Bot क्या है?', ask: 'Order Bot क्या है?' },
        supportBot: { label: 'Support Bot क्या है?', ask: 'Support Bot क्या है?' },
        pricing: { label: 'कितना खर्च आता है?', ask: 'इसकी कीमत कितनी है?' },
        start: { label: 'कैसे शुरू करूँ?', ask: 'मैं कैसे शुरू करूँ?' },
        ownNumber: { label: 'मेरा अपना नंबर?', ask: 'क्या मैं अपना WhatsApp नंबर इस्तेमाल कर सकता हूँ?' },
        languages: { label: 'कौन सी भाषाएँ?', ask: 'बॉट कौन सी भाषाएँ बोलता है?' },
    },
    openers: {
        home: 'मैं Auto Resellers Hub का असिस्टेंट हूँ। कुछ भी पूछें — पैनल क्या है, सेटअप कैसे होता है, कीमत क्या है। मैं आपकी भाषा में जवाब देता हूँ।',
        pricing: 'प्लान की तुलना कर रहे हैं? मैं बता सकता हूँ कि हर एक क्या करता है और उसकी कीमत क्या है।',
        try: 'प्रैक्टिस चैट में घूमकर देखें — और जो समझ न आए मुझसे पूछें।',
    },
};

const tr: Partial2<Strings> = {
    status: 'Anında yanıtlar',
    open: 'Auto Resellers Hub asistanını aç',
    close: 'Kapat',
    restart: 'Baştan başla',
    send: 'Gönder',
    placeholder: 'Her şeyi sorabilirsiniz…',
    footnote: 'Yapay zekâ hata yapabilir — fiyatları fiyat sayfasından kontrol edin',
    greeting: 'Merhaba 👋',
    thinking: 'Düşünüyor',
    peekTitle: 'Botlar hakkında sorunuz mu var?',
    peekBody: 'Bana sorun — kendi dilinizde.',
    language: 'Dil',
    autoDetect: 'Otomatik algıla',
    copy: 'Yanıtı kopyala',
    copied: 'Kopyalandı',
    listen: 'Sorunuzu sesle söyleyin',
    listening: 'Dinliyorum…',
    popular: 'Sık sorulan sorular',
    tryTitle: 'Gerçek botu deneyin',
    tryBody: 'Bir telefon ekranında onunla sohbet edin. Kayıt gerekmez.',
    needPerson: 'Bir insanla mı görüşmek istersiniz?',
    leaveDetails: 'Bilgilerinizi bırakın',
    failed: 'Gönderilemedi. Biraz sonra tekrar deneyin veya bize WhatsApp\'tan ulaşın.',
    askAgain: 'Tekrar sor',
    slowDown: "Çok hızlı soruyorsunuz — birkaç saniye bekleyip tekrar deneyin.",
    leadTitle: 'Bilgilerinizi bırakın',
    leadBody: 'WhatsApp üzerinden yanıtlayacağız. Şu ana kadarki sorunuz da iletilir.',
    leadName: 'Adınız',
    leadPhone: 'WhatsApp numarası',
    leadExtra: 'Eklemek istediğiniz bir şey',
    optional: '(isteğe bağlı)',
    back: 'Geri',
    sendToSupport: 'Desteğe gönder',
    leadFailed: 'Gönderilemedi. Tekrar deneyin veya bize WhatsApp\'tan ulaşın.',
    quick: {
        orderBot: { label: 'Order Bot nedir?', ask: 'Order Bot nedir?' },
        supportBot: { label: 'Support Bot nedir?', ask: 'Support Bot nedir?' },
        pricing: { label: 'Ne kadar tutar?', ask: 'Ne kadar tutar?' },
        start: { label: 'Nasıl başlarım?', ask: 'Nasıl başlayabilirim?' },
        ownNumber: { label: 'Kendi numaram?', ask: 'Kendi WhatsApp numaramı kullanabilir miyim?' },
        languages: { label: 'Hangi diller?', ask: 'Bot hangi dilleri konuşuyor?' },
    },
    openers: {
        home: 'Ben Auto Resellers Hub asistanıyım. Her şeyi sorun: panel nedir, kurulum nasıl olur, ne kadar tutar. Sizin dilinizde yanıt veririm.',
        pricing: 'Planları mı karşılaştırıyorsunuz? Her birinin ne yaptığını ve ne kadar tuttuğunu anlatabilirim.',
        try: 'Deneme sohbetini gezin — anlamadığınız her şeyi bana sorun.',
    },
};

const de: Partial2<Strings> = {
    status: 'Antwortet sofort',
    open: 'Auto-Resellers-Hub-Assistent öffnen',
    close: 'Schließen',
    restart: 'Neu beginnen',
    send: 'Senden',
    placeholder: 'Fragen Sie, was Sie möchten…',
    footnote: 'KI kann sich irren — Preise bitte auf der Preisseite prüfen',
    greeting: 'Hallo 👋',
    thinking: 'Denkt nach',
    peekTitle: 'Fragen zu den Bots?',
    peekBody: 'Fragen Sie mich — in Ihrer Sprache.',
    language: 'Sprache',
    autoDetect: 'Automatisch erkennen',
    copy: 'Antwort kopieren',
    copied: 'Kopiert',
    listen: 'Frage einsprechen',
    listening: 'Ich höre zu…',
    popular: 'Häufige Fragen',
    tryTitle: 'Den echten Bot testen',
    tryBody: 'Chatten Sie auf einem Handy-Bildschirm mit ihm. Ohne Anmeldung.',
    needPerson: 'Möchten Sie mit einer Person sprechen?',
    leaveDetails: 'Kontaktdaten hinterlassen',
    failed: 'Das hat nicht geklappt. Versuchen Sie es gleich noch einmal oder schreiben Sie uns per WhatsApp.',
    askAgain: 'Erneut fragen',
    slowDown: "Sie fragen sehr schnell — warten Sie ein paar Sekunden und versuchen Sie es erneut.",
    leadTitle: 'Kontaktdaten hinterlassen',
    leadBody: 'Wir antworten per WhatsApp. Ihre bisherige Frage wird mitgeschickt.',
    leadName: 'Ihr Name',
    leadPhone: 'WhatsApp-Nummer',
    leadExtra: 'Möchten Sie etwas ergänzen?',
    optional: '(optional)',
    back: 'Zurück',
    sendToSupport: 'An den Support senden',
    leadFailed: 'Senden fehlgeschlagen. Bitte erneut versuchen oder per WhatsApp schreiben.',
    quick: {
        orderBot: { label: 'Was ist der Order Bot?', ask: 'Was ist der Order Bot?' },
        supportBot: { label: 'Was ist der Support Bot?', ask: 'Was ist der Support Bot?' },
        pricing: { label: 'Was kostet es?', ask: 'Was kostet es?' },
        start: { label: 'Wie fange ich an?', ask: 'Wie fange ich an?' },
        ownNumber: { label: 'Eigene Nummer?', ask: 'Kann ich meine eigene WhatsApp-Nummer verwenden?' },
        languages: { label: 'Welche Sprachen?', ask: 'Welche Sprachen spricht der Bot?' },
    },
    openers: {
        home: 'Ich bin der Assistent von Auto Resellers Hub. Fragen Sie mich alles: was ein Panel ist, wie die Einrichtung abläuft, was es kostet. Ich antworte in Ihrer Sprache.',
        pricing: 'Vergleichen Sie die Tarife? Ich erkläre gern, was jeder leistet und was er kostet.',
        try: 'Probieren Sie den Test-Chat aus — und fragen Sie mich, was unklar ist.',
    },
};

const id: Partial2<Strings> = {
    status: 'Menjawab seketika',
    open: 'Buka asisten Auto Resellers Hub',
    close: 'Tutup',
    restart: 'Mulai ulang',
    send: 'Kirim',
    placeholder: 'Tanyakan apa saja…',
    footnote: 'AI bisa salah — cek harga di halaman harga',
    greeting: 'Halo 👋',
    thinking: 'Berpikir',
    peekTitle: 'Ada pertanyaan soal bot?',
    peekBody: 'Tanyakan saja — dalam bahasa Anda.',
    language: 'Bahasa',
    autoDetect: 'Deteksi otomatis',
    copy: 'Salin jawaban',
    copied: 'Tersalin',
    listen: 'Ucapkan pertanyaan Anda',
    listening: 'Mendengarkan…',
    popular: 'Pertanyaan populer',
    tryTitle: 'Coba bot sungguhan',
    tryBody: 'Ngobrol dengannya di layar ponsel. Tanpa daftar.',
    needPerson: 'Butuh bicara dengan orang?',
    leaveDetails: 'Tinggalkan data',
    failed: 'Belum terkirim. Coba lagi sebentar lagi, atau hubungi kami lewat WhatsApp.',
    askAgain: 'Tanya lagi',
    slowDown: "Anda bertanya terlalu cepat — tunggu beberapa detik lalu coba lagi.",
    leadTitle: 'Tinggalkan data Anda',
    leadBody: 'Kami akan membalas lewat WhatsApp. Pertanyaan Anda sejauh ini ikut terkirim.',
    leadName: 'Nama Anda',
    leadPhone: 'Nomor WhatsApp',
    leadExtra: 'Ada yang ingin ditambahkan',
    optional: '(opsional)',
    back: 'Kembali',
    sendToSupport: 'Kirim ke dukungan',
    leadFailed: 'Gagal terkirim. Coba lagi, atau hubungi kami lewat WhatsApp.',
    quick: {
        orderBot: { label: 'Apa itu Order Bot?', ask: 'Apa itu Order Bot?' },
        supportBot: { label: 'Apa itu Support Bot?', ask: 'Apa itu Support Bot?' },
        pricing: { label: 'Berapa harganya?', ask: 'Berapa biayanya?' },
        start: { label: 'Cara memulai?', ask: 'Bagaimana cara memulai?' },
        ownNumber: { label: 'Nomor sendiri?', ask: 'Bisakah saya memakai nomor WhatsApp sendiri?' },
        languages: { label: 'Bahasa apa saja?', ask: 'Bot berbicara dalam bahasa apa saja?' },
    },
    openers: {
        home: 'Saya asisten Auto Resellers Hub. Tanyakan apa saja: apa itu panel, bagaimana pengaturannya, berapa biayanya. Saya menjawab dalam bahasa Anda.',
        pricing: 'Membandingkan paket? Saya bisa jelaskan fungsi dan harga masing-masing.',
        try: 'Jelajahi chat percobaan — dan tanyakan apa pun yang belum jelas.',
    },
};

const ru: Partial2<Strings> = {
    status: 'Отвечает мгновенно',
    open: 'Открыть ассистента Auto Resellers Hub',
    close: 'Закрыть',
    restart: 'Начать заново',
    send: 'Отправить',
    placeholder: 'Спросите что угодно…',
    footnote: 'ИИ может ошибаться — проверяйте цены на странице тарифов',
    greeting: 'Здравствуйте 👋',
    thinking: 'Думает',
    peekTitle: 'Вопросы о ботах?',
    peekBody: 'Спросите — на вашем языке.',
    language: 'Язык',
    autoDetect: 'Определять автоматически',
    copy: 'Скопировать ответ',
    copied: 'Скопировано',
    listen: 'Продиктовать вопрос',
    listening: 'Слушаю…',
    popular: 'Частые вопросы',
    tryTitle: 'Попробуйте настоящего бота',
    tryBody: 'Пообщайтесь с ним на экране телефона. Без регистрации.',
    needPerson: 'Нужен живой человек?',
    leaveDetails: 'Оставить контакты',
    failed: 'Не отправилось. Попробуйте ещё раз чуть позже или напишите нам в WhatsApp.',
    askAgain: 'Спросить снова',
    slowDown: "Вы спрашиваете слишком быстро — подождите несколько секунд и попробуйте снова.",
    leadTitle: 'Оставьте контакты',
    leadBody: 'Мы ответим в WhatsApp. Ваш вопрос будет приложен.',
    leadName: 'Ваше имя',
    leadPhone: 'Номер WhatsApp',
    leadExtra: 'Что-то добавить',
    optional: '(необязательно)',
    back: 'Назад',
    sendToSupport: 'Отправить в поддержку',
    leadFailed: 'Не удалось отправить. Попробуйте ещё раз или напишите в WhatsApp.',
    quick: {
        orderBot: { label: 'Что такое Order Bot?', ask: 'Что такое Order Bot?' },
        supportBot: { label: 'Что такое Support Bot?', ask: 'Что такое Support Bot?' },
        pricing: { label: 'Сколько стоит?', ask: 'Сколько это стоит?' },
        start: { label: 'Как начать?', ask: 'Как начать?' },
        ownNumber: { label: 'Свой номер?', ask: 'Могу ли я использовать свой номер WhatsApp?' },
        languages: { label: 'Какие языки?', ask: 'На каких языках говорит бот?' },
    },
    openers: {
        home: 'Я ассистент Auto Resellers Hub. Спрашивайте что угодно: что такое панель, как проходит настройка, сколько это стоит. Отвечаю на вашем языке.',
        pricing: 'Сравниваете тарифы? Расскажу, что делает каждый и сколько стоит.',
        try: 'Походите по тестовому чату — и спросите меня, если что-то неясно.',
    },
};

const zh: Partial2<Strings> = {
    status: '即时回复',
    open: '打开 Auto Resellers Hub 助手',
    close: '关闭',
    restart: '重新开始',
    send: '发送',
    placeholder: '随便问点什么…',
    footnote: 'AI 可能出错——价格请以价格页面为准',
    greeting: '你好 👋',
    thinking: '思考中',
    peekTitle: '对机器人有疑问？',
    peekBody: '直接问我——用你的语言。',
    language: '语言',
    autoDetect: '自动识别',
    copy: '复制回答',
    copied: '已复制',
    listen: '语音提问',
    listening: '正在听…',
    popular: '常见问题',
    tryTitle: '试用真实机器人',
    tryBody: '在手机屏幕上和它聊天，无需注册。',
    needPerson: '需要真人帮助吗？',
    leaveDetails: '留下联系方式',
    failed: '发送失败。请稍后再试，或通过 WhatsApp 联系我们。',
    askAgain: '再问一次',
    slowDown: "您提问太快了——请稍等几秒再试。",
    leadTitle: '留下您的联系方式',
    leadBody: '我们会通过 WhatsApp 回复您，您之前的问题会一并附上。',
    leadName: '您的姓名',
    leadPhone: 'WhatsApp 号码',
    leadExtra: '还有什么要补充的',
    optional: '（选填）',
    back: '返回',
    sendToSupport: '发送给客服',
    leadFailed: '发送失败。请重试，或通过 WhatsApp 联系我们。',
    quick: {
        orderBot: { label: '什么是 Order Bot？', ask: '什么是 Order Bot？' },
        supportBot: { label: '什么是 Support Bot？', ask: '什么是 Support Bot？' },
        pricing: { label: '多少钱？', ask: '费用是多少？' },
        start: { label: '如何开始？', ask: '我该如何开始？' },
        ownNumber: { label: '用自己的号码？', ask: '我可以使用自己的 WhatsApp 号码吗？' },
        languages: { label: '支持哪些语言？', ask: '机器人支持哪些语言？' },
    },
    openers: {
        home: '我是 Auto Resellers Hub 的助手。什么都可以问：什么是面板、如何设置、费用多少。我会用你的语言回答。',
        pricing: '正在比较套餐？我可以讲讲每个套餐的作用和价格。',
        try: '体验一下演示聊天——有不明白的随时问我。',
    },
};

const DICTIONARIES: Record<string, Partial2<Strings>> = { sw, fr, es, pt, ar, hi, tr, de, id, ru, zh };

/** English underneath, the visitor's language laid over it. */
export function t(locale: Locale): Strings {
    const over = DICTIONARIES[locale];

    if (!over) {
        return en;
    }

    return {
        ...en,
        ...(over as Partial<Strings>),
        quick: { ...en.quick, ...(over.quick ?? {}) },
        openers: { ...en.openers, ...(over.openers ?? {}) },
    } as Strings;
}

/** The picker: the languages by their own names, and which read right to left. */
export const LANGUAGES: Array<{ code: string; name: string; rtl?: boolean }> = [
    { code: 'en', name: 'English' },
    { code: 'sw', name: 'Kiswahili' },
    { code: 'fr', name: 'Français' },
    { code: 'es', name: 'Español' },
    { code: 'pt', name: 'Português' },
    { code: 'ar', name: 'العربية', rtl: true },
    { code: 'hi', name: 'हिन्दी' },
    { code: 'tr', name: 'Türkçe' },
    { code: 'de', name: 'Deutsch' },
    { code: 'id', name: 'Bahasa Indonesia' },
    { code: 'ru', name: 'Русский' },
    { code: 'zh', name: '中文' },
    { code: 'it', name: 'Italiano' },
    { code: 'ja', name: '日本語' },
    { code: 'ko', name: '한국어' },
];

export function isRtl(locale: string): boolean {
    return LANGUAGES.find((language) => language.code === locale)?.rtl === true;
}

/** The speech-recognition language tag for the microphone. */
export const SPEECH: Record<string, string> = {
    en: 'en-US', sw: 'sw-KE', fr: 'fr-FR', es: 'es-ES', pt: 'pt-BR', ar: 'ar-SA', hi: 'hi-IN',
    tr: 'tr-TR', de: 'de-DE', id: 'id-ID', ru: 'ru-RU', zh: 'zh-CN', it: 'it-IT', ja: 'ja-JP', ko: 'ko-KR',
};
